---
abstract: 'tarantool 1.5 to 1.6 stream database converter'
author:
  - 'Dmitry E. Oboukhov <unera@debian.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: tntcompat
no_index:
  directory:
    - t
    - inc
requires:
  AnyEvent::Socket: 0
  Carp: 0
  Coro: 0
  Coro::AnyEvent: 0
  Coro::Handle: 0
  Data::Dumper: 0
  Digest::SHA: 0
  Encode: 0
  Errno: 0
  JSON::XS: 0
  List::MoreUtils: 0
  MIME::Base64: 0
  Scalar::Util: 0
  Time::HiRes: 0
  UUID: 0
resources:
  bugtracker: https://github.com/tarantool/compat-flow/issues
  homepage: https://github.com/tarantool/compat-flow
  repository: https://github.com/tarantool/compat-flow
version: 0.4
